services:
  processor:
    build:
      context: .
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TABLE=webpagecrowler
      - BATCH_SIZE=20
      - TIME_OUT=18
    command: ["python", "processor.py"]