services:
  web:
    build:
      context: .
    ports:
      - 5000:5555
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TABLE=webpagecrawler
      - BATCH_SIZE=20
      - TIME_OUT=18
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: ["gunicorn", "app:app", "--bind", "0.0.0.0:5555"]
    restart: unless-stopped