services:
  web:
    build:
      context: .
    ports:
      - 5000:5555
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - yt_ex

networks:
  yt_ex:
    driver: bridge